/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExamplePreset {
  'id' : string,
  'title' : string,
  'expectedOutput' : string,
  'description' : string,
  'sampleInput' : string,
  'topicId' : string,
}
export interface Lesson { 'id' : string, 'title' : string, 'content' : string }
export interface Topic {
  'id' : string,
  'title' : string,
  'description' : string,
  'lessons' : Array<Lesson>,
}
export interface _SERVICE {
  'addExamplePreset' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'addLessonToTopic' : ActorMethod<[string, string, string, string], undefined>,
  'addTopic' : ActorMethod<[string, string, string], undefined>,
  'getAllTopics' : ActorMethod<[], Array<Topic>>,
  'getExamplePresetsForTopic' : ActorMethod<[string], Array<ExamplePreset>>,
  'getLessonsForTopic' : ActorMethod<[string], Array<Lesson>>,
  'getTopic' : ActorMethod<[string], [] | [Topic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];