/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Topic = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
});
export const ExamplePreset = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'expectedOutput' : IDL.Text,
  'description' : IDL.Text,
  'sampleInput' : IDL.Text,
  'topicId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addExamplePreset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addLessonToTopic' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addTopic' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getExamplePresetsForTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExamplePreset)],
      ['query'],
    ),
  'getLessonsForTopic' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getTopic' : IDL.Func([IDL.Text], [IDL.Opt(Topic)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Topic = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
  });
  const ExamplePreset = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'expectedOutput' : IDL.Text,
    'description' : IDL.Text,
    'sampleInput' : IDL.Text,
    'topicId' : IDL.Text,
  });
  
  return IDL.Service({
    'addExamplePreset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addLessonToTopic' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addTopic' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getExamplePresetsForTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamplePreset)],
        ['query'],
      ),
    'getLessonsForTopic' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getTopic' : IDL.Func([IDL.Text], [IDL.Opt(Topic)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };